# Generated by Django 3.2.9 on 2021-12-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211217_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlethema',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterUniqueTogether(
            name='articlethema',
            unique_together={('article', 'thema')},
        ),
    ]
