# Generated by Django 3.2.9 on 2021-12-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211218_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlethema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articlethema',
            unique_together=set(),
        ),
    ]
