# Generated by Django 3.2.9 on 2021-12-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211219_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlethema',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RenameField(
            model_name='thema',
            old_name='thema',
            new_name='thema_thema',
        ),
    ]
