# Generated by Django 3.2.9 on 2021-12-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_thema_thema_thema_thema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlethema',
            unique_together=set(),
        ),
    ]
